```mermaid
graph LR
  Core --> NetworkingShared
  NetworkingShared --> NetworkingClient
  NetworkingShared --> NetworkingServer
  NetworkingServer --> DedicatedServer
  NetworkingClient --> ClientApp
```